### ISSUE TITLE
Valid exotic YAML syntax unsupported by the plugin

### ISSUE THREAD

**Issue by AdrienGiboire** [lmeijvogel/vim-yaml-helper#14]
I have the following:

```
---
en-US:
  ? " \r\noctoprime"
  : creators:
      menu:
        collections: Collections
  activerecord:
    attributes:
      brand:
```

This totally makes the plugin unusable. Is there a way to arrange this?

**Comment by lmeijvogel** [comment]
Hey, thanks for the report!

I'm afraid that I don't know enough about YAML in this case: Do the `?` and `:` have special meaning?
Running through Ruby's YAML gives this result:
```ruby
# Ruby 2.3.1p112
# pp YAML.load(input)
{
  "en-US" => {
    " octoprime" => {
      "creators" => {
        "menu" => {
          "collections" => "Collections"
        }
      }
    },
    "activerecord" => {
      "attributes" => {
        "brand" => "Brand"
      }
    }
  }
}
```
Is that the expected output? (Value for `activerecord.attributes.brand` added).

The plugin currently works with indentation and pattern matching, I doubt that it's doable to rewrite it to support more complex behavior, that would require more YAML-knowledge than the plugin currently has (actually running the yaml through a parser, maybe?).

If you can make a PR, I can look at it, but I don't work much with the plugin or yaml anymore, so I'm afraid that I won't have the time to write it myself.

**Comment by AdrienGiboire** [comment]
I don't really know the sense of this. It's been produced by Phraseapp and Rails does not complain so I guessed this is legit YAML.

**Comment by lmeijvogel** [comment]
Hey, just a heads-up that I'm not going to do much work on this plugin anymore: I haven't used YAML in over a year and I've practically stopped using vim. I'll be closing this issue.

If someone wants to try and fix it, I can of course see if I can merge a PR.
